[package]
name = "ReacTXT"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
hyper = { version = "1.3.1", features = ["full"] }
tokio = { version = "1.38.0", features = ["full"] }
tower = "0.4.13"
tracing-subscriber = "0.3.18"
